const SEND_LOGIN_QUERY = "SEND_LOGIN_QUERY";
const LOGIN_SUCCESSFULL = "LOGIN_SUCCESSFULL";
const LOGIN_FAIL = "LOGIN_FAIL";

const SEND_GOOGLE_QUERY = "SEND_GOOGLE_QUERY";
const LOGIN_GOOGLE_SUCCESSFULL = "LOGIN_GOOGLE_SUCCESSFULL";
const LOGIN_GOOGLE_FAIL = "LOGIN_GOOGLE_FAIL";

const SEND_FACEBOOK_QUERY = "SEND_FACEBOOK_QUERY";
const LOGIN_FACEBOOK_SUCCESSFULL = "LOGIN_FACEBOOK_SUCCESSFULL";
const LOGIN_FACEBOOK_FAIL = "LOGIN_FACEBOOK_FAIL";

const LOGOUT = "LOGOUT"

export {SEND_LOGIN_QUERY,LOGIN_SUCCESSFULL,LOGIN_FAIL,SEND_GOOGLE_QUERY,LOGIN_GOOGLE_SUCCESSFULL,LOGIN_GOOGLE_FAIL,SEND_FACEBOOK_QUERY,LOGIN_FACEBOOK_SUCCESSFULL,LOGIN_FACEBOOK_FAIL,LOGOUT}