export const FETCH_RECOVERY_REQUEST = "FETCH_RECOVERY_REQUEST";
export const FETCH_RECOVERY_SUCCESS = "FETCH_RECOVERY_SUCCESS";
export const FETCH_RECOVERY_FAILURE = "FETCH_RECOVERY_FAILURE";
export const FETCH_RESET_REQUEST = "FETCH_RESET_REQUEST";
export const FETCH_RESET_SUCCESS = "FETCH_RESET_SUCCESS";
export const FETCH_RESET_FAILURE = "FETCH_RESET_FAILURE";
