const BASIC_QUERY = "BASIC_QUERY"
const BASIC_QUERY_SUCCESS = "BASIC_QUERY_SUCCESS"
const BASIC_QUERY_FAIL = "BASIC_QUERY_FAIL"

const BOOKING_QUERY = "BOOKING_QUERY"
const BOOKING_QUERY_SUCCESS = "BOOKING_QUERY_SUCCESS"
const BOOKING_QUERY_FAIL = "BOOKING_QUERY_FAIL"

const AREA_QUERY = "AREA_QUERY"
const AREA_QUERY_SUCCESS = "AREA_QUERY_SUCCESS"
const AREA_QUERY_FAIL = "AREA_QUERY_FAIL"

export {BASIC_QUERY,BASIC_QUERY_SUCCESS,BASIC_QUERY_FAIL,BOOKING_QUERY,BOOKING_QUERY_SUCCESS,BOOKING_QUERY_FAIL,AREA_QUERY,AREA_QUERY_SUCCESS,AREA_QUERY_FAIL}