const PAYMENT_QUERY = "PAYMENT_QUERY"
const PAYMENT_SUCCESS = "PAYMENT_SUCCESS"
const PAYMENT_FAIL = "PAYMENT_FAIL"

const BOOKING_QUERY = "BOOKING_QUERY"
const BOOKING_SUCCESS = "BOOKING_SUCCESS"
const BOOKING_FAIL = "BOOKING_FAIL"

const RESET_PAYMENT = "RESET_PAYMENT"

export { RESET_PAYMENT, PAYMENT_QUERY, PAYMENT_SUCCESS, PAYMENT_FAIL, BOOKING_QUERY, BOOKING_SUCCESS, BOOKING_FAIL }