const CHECK_DATES_QUERY = "CHECK_DATES_QUERY"
const CHECK_DATES_SUCCESS = "CHECK_DATES_SUCCESS"
const CHECK_DATES_FAIL = "CHECK_DATES_FAIL"

const SET_QUERY_FALSE = "SET_QUERY_FALSE"

export { CHECK_DATES_QUERY, CHECK_DATES_SUCCESS, CHECK_DATES_FAIL, SET_QUERY_FALSE }