const SEND_REGISTER_QUERY = "SEND_REGISTER_QUERY";
const REGISTER_SUCCESSFULL = "REGISTER_SUCCESSFULL";
const REGISTER_FAIL = "REGISTER_FAIL";

export {SEND_REGISTER_QUERY,REGISTER_SUCCESSFULL,REGISTER_FAIL}